import { useEffect, useState } from "react";

// Generated by tauri-specta from the Rust command signatures in
// src-tauri/src/diagnostics.rs -- gitignored, not committed. Regenerated
// by `cargo test -p nacc-app` (see src-tauri/tests/export_bindings.rs)
// before this file is type-checked, both in CI and for local development
// once a real Rust build is possible on the developer's machine. See
// docs/architecture/overview.md for the current, honestly-documented
// limitation this creates on a machine where the Rust side cannot link.
import { commands, type AppDiagnostics } from "./bindings";

/**
 * Phase 1's one real, end-to-end typed IPC round trip: calls the Rust
 * `get_app_diagnostics` command and renders the result. Not a real
 * feature screen -- Projects, the Role Matrix, and every other page in
 * the master plan's information architecture (S17) are later phases.
 * This exists to prove the pipe works.
 */
export default function App() {
  const [diagnostics, setDiagnostics] = useState<AppDiagnostics | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    commands
      .getAppDiagnostics()
      .then((result) => {
        if (!cancelled) setDiagnostics(result);
      })
      .catch((err: unknown) => {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err));
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <main className="app">
      <h1>Native Agent Control Center</h1>

      {error && (
        <p role="alert" data-testid="diagnostics-error">
          Failed to load diagnostics: {error}
        </p>
      )}

      {!error && !diagnostics && <p data-testid="diagnostics-loading">Loading diagnostics...</p>}

      {diagnostics && (
        <dl data-testid="diagnostics">
          <dt>App version</dt>
          <dd data-testid="app-version">{diagnostics.app_version}</dd>

          <dt>Workspace crates</dt>
          <dd data-testid="workspace-crate-count">{diagnostics.workspace_crate_count}</dd>

          <dt>Minimum Rust version</dt>
          <dd data-testid="minimum-rust-version">{diagnostics.minimum_rust_version}</dd>

          <dt>Dev mode</dt>
          <dd data-testid="dev-mode">{diagnostics.dev_mode ? "yes" : "no"}</dd>

          <dt>Sample workflow run id</dt>
          <dd data-testid="sample-workflow-run-id">{diagnostics.sample_workflow_run_id}</dd>
        </dl>
      )}
    </main>
  );
}
