import { useEffect, useState } from "react";

// Generated by tauri-specta from the Rust command signatures in
// src-tauri/src/diagnostics.rs -- gitignored, not committed. Regenerated by
// `cargo run -p nacc-app -- --export-bindings` (see src-tauri/src/main.rs)
// before this file is type-checked, both in CI and for local development
// once a real Rust build is possible on the developer's machine. See
// docs/architecture/overview.md for the current, honestly-documented
// limitation this creates on a machine where the Rust side cannot link.
import { commands, type AppDiagnostics } from "./bindings";

/**
 * Phase 1's one real, end-to-end typed IPC round trip, extended in Phase 2
 * into a real storage round trip too: `get_app_diagnostics` now returns
 * `Result<AppDiagnostics, String>`, which tauri-specta wraps as
 * `{status:"ok",data} | {status:"error",error}` rather than a rejected
 * promise (verified against tauri-specta 2.0.0-rc.25's own codegen source,
 * not assumed) -- narrow on `status` below rather than `try`/`catch`.
 * Not a real feature screen -- Projects, the Role Matrix, and every other
 * page in the master plan's information architecture (S17) are later
 * phases. This exists to prove the pipe works.
 */
export default function App() {
  const [diagnostics, setDiagnostics] = useState<AppDiagnostics | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    commands
      .getAppDiagnostics()
      .then((result) => {
        if (cancelled) return;
        if (result.status === "ok") {
          setDiagnostics(result.data);
        } else {
          setError(result.error);
        }
      })
      .catch((err: unknown) => {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err));
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <main className="app">
      <h1>Native Agent Control Center</h1>

      {error && (
        <p role="alert" data-testid="diagnostics-error">
          Failed to load diagnostics: {error}
        </p>
      )}

      {!error && !diagnostics && <p data-testid="diagnostics-loading">Loading diagnostics...</p>}

      {diagnostics && (
        <dl data-testid="diagnostics">
          <dt>App version</dt>
          <dd data-testid="app-version">{diagnostics.app_version}</dd>

          <dt>Workspace crates</dt>
          <dd data-testid="workspace-crate-count">{diagnostics.workspace_crate_count}</dd>

          <dt>Minimum Rust version</dt>
          <dd data-testid="minimum-rust-version">{diagnostics.minimum_rust_version}</dd>

          <dt>Dev mode</dt>
          <dd data-testid="dev-mode">{diagnostics.dev_mode ? "yes" : "no"}</dd>

          <dt>Sample workflow run id</dt>
          <dd data-testid="sample-workflow-run-id">{diagnostics.sample_workflow_run_id}</dd>

          <dt>Storage schema version</dt>
          <dd data-testid="storage-schema-version">{diagnostics.storage_schema_version}</dd>

          <dt>Diagnostics requests recorded</dt>
          <dd data-testid="diagnostics-requests-recorded">
            {diagnostics.diagnostics_requests_recorded}
          </dd>
        </dl>
      )}
    </main>
  );
}
