// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getAppDiagnostics: () => typedError<AppDiagnostics, string>(__TAURI_INVOKE("get_app_diagnostics")),
	listRoleProfiles: () => typedError<RoleProfileView[], string>(__TAURI_INVOKE("list_role_profiles")),
	createRoleProfile: (args: CreateRoleProfileArgs) => typedError<RoleProfileMutation, string>(__TAURI_INVOKE("create_role_profile", { args })),
	updateRoleProfile: (id: RoleProfileId, update: RoleProfileUpdate) => typedError<RoleProfileMutation, string>(__TAURI_INVOKE("update_role_profile", { id, update })),
	setRoleProfileEnabled: (id: RoleProfileId, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_role_profile_enabled", { id, enabled })),
	deleteRoleProfile: (id: RoleProfileId) => typedError<boolean, string>(__TAURI_INVOKE("delete_role_profile", { id })),
	detectProvider: (args: DetectProviderArgs) => typedError<ProviderInstallationView, string>(__TAURI_INVOKE("detect_provider", { args })),
	listProviderInstallations: () => typedError<ProviderInstallationView[], string>(__TAURI_INVOKE("list_provider_installations")),
	checkProviderAuth: (args: DetectProviderArgs) => typedError<AuthProbeView, string>(__TAURI_INVOKE("check_provider_auth", { args })),
	listWorkflowTemplates: () => typedError<WorkflowTemplateView[], string>(__TAURI_INVOKE("list_workflow_templates")),
	/**
	 *  Load the complete graph for one template so the GUI can inspect or edit
	 *  it without reconstructing node settings from the summary list.
	 */
	getWorkflowTemplate: (args: TemplateNameArgs) => typedError<WorkflowTemplateDefinitionView, string>(__TAURI_INVOKE("get_workflow_template", { args })),
	startWorkflowRun: (args: StartRunArgs) => typedError<RunSnapshotView, string>(__TAURI_INVOKE("start_workflow_run", { args })),
	getWorkflowRun: (args: RunIdArgs) => typedError<RunSnapshotView, string>(__TAURI_INVOKE("get_workflow_run", { args })),
	listWorkflowRuns: () => typedError<WorkflowRunView[], string>(__TAURI_INVOKE("list_workflow_runs")),
	pauseWorkflowRun: (args: ReasonArgs) => typedError<RunSnapshotView, string>(__TAURI_INVOKE("pause_workflow_run", { args })),
	cancelWorkflowRun: (args: ReasonArgs) => typedError<RunSnapshotView, string>(__TAURI_INVOKE("cancel_workflow_run", { args })),
	resumeWorkflowRun: (args: RunIdArgs) => typedError<RunSnapshotView, string>(__TAURI_INVOKE("resume_workflow_run", { args })),
	decideWorkflowApproval: (args: DecideApprovalArgs) => typedError<RunSnapshotView, string>(__TAURI_INVOKE("decide_workflow_approval", { args })),
	listWorkflowEvents: (args: RunIdArgs) => typedError<WorkflowEventView[], string>(__TAURI_INVOKE("list_workflow_events", { args })),
	/**
	 *  Create or update a *custom* workflow template. The DAG is validated
	 *  before it is stored, so a graph that could never run cannot even be
	 *  saved; built-in names are refused because presets are the product's own
	 *  contract with the user.
	 */
	saveWorkflowTemplate: (args: SaveTemplateArgs) => typedError<WorkflowTemplateView, string>(__TAURI_INVOKE("save_workflow_template", { args })),
	/**
	 *  Delete a *custom* template. Built-ins refuse with a typed error: the
	 *  presets are part of what NACC ships.
	 */
	deleteWorkflowTemplate: (args: TemplateNameArgs) => typedError<boolean, string>(__TAURI_INVOKE("delete_workflow_template", { args })),
	/**
	 *  Probe one provider's capabilities live through its adapter and persist the
	 *  snapshot (master plan S8.3: "store a timestamped snapshot and refresh it
	 *  on demand"). Only registered adapters can be probed; an unknown provider
	 *  is a typed error, never a guessed answer.
	 */
	probeProviderCapabilities: (args: DetectProviderArgs) => typedError<CapabilitySnapshotView, string>(__TAURI_INVOKE("probe_provider_capabilities", { args })),
	/**
	 *  The most recent persisted snapshot for one provider on native Windows,
	 *  if any. This is what the Role Matrix reads to decide whether a
	 *  thinking/reasoning control may honestly be enabled -- and a GUI must
	 *  treat `None` as "disabled with an explanation", never as a default.
	 */
	latestProviderCapabilities: (args: DetectProviderArgs) => typedError<{
	provider: ProviderId,
	installed: boolean,
	version: string | null,
	authenticated: boolean,
	/**
	 *  Adapter-declared health, snake_case ("ready", "not_installed",
	 *  "unauthenticated", ...). A GUI shows it; nothing infers readiness.
	 */
	health: string,
	models: ModelCapabilityView[],
	checked_at_millis: string,
} | null, string>(__TAURI_INVOKE("latest_provider_capabilities", { args })),
	/**
	 *  Detect the local prerequisites the Setup Wizard names (master plan
	 *  S17.1 step 2): git, optionally the GitHub CLI, and the registered agent
	 *  CLIs (those are `providers::detect_provider`'s job -- the wizard lists
	 *  them from the persisted installations rather than re-probing here).
	 */
	checkPrerequisites: (args: CheckPrerequisitesArgs) => typedError<PrerequisiteView[], string>(__TAURI_INVOKE("check_prerequisites", { args })),
	/**
	 *  Read-only validation of a candidate workspace (master plan S17.1 step 12):
	 *  is it an absolute existing directory, and is it inside a git repository?
	 *  Writes nothing anywhere.
	 */
	checkWorkspace: (args: CheckWorkspaceArgs) => typedError<WorkspaceCheckView, string>(__TAURI_INVOKE("check_workspace", { args })),
	getGithubAuthStatus: () => typedError<GithubAuthStatus, string>(__TAURI_INVOKE("get_github_auth_status")),
	getGithubRepository: (args: GithubRepositoryArgs) => typedError<RepositorySummary, string>(__TAURI_INVOKE("get_github_repository", { args })),
	listGithubBranches: (args: GithubListArgs) => typedError<BranchSummary[], string>(__TAURI_INVOKE("list_github_branches", { args })),
	listGithubPullRequests: (args: GithubListArgs) => typedError<PullRequestSummary[], string>(__TAURI_INVOKE("list_github_pull_requests", { args })),
	listGithubCheckRuns: (args: GithubChecksArgs) => typedError<CheckRunSummary[], string>(__TAURI_INVOKE("list_github_check_runs", { args })),
	listGithubWorkflowRuns: (args: GithubListArgs) => typedError<WorkflowRunSummary[], string>(__TAURI_INVOKE("list_github_workflow_runs", { args })),
	listGithubWorkflowJobs: (args: GithubRunArgs) => typedError<WorkflowJobSummary[], string>(__TAURI_INVOKE("list_github_workflow_jobs", { args })),
	getGithubFailedRunEvidence: (args: GithubRunArgs) => typedError<FailedRunEvidence[], string>(__TAURI_INVOKE("get_github_failed_run_evidence", { args })),
	listGithubArtifacts: (args: GithubListArgs) => typedError<ArtifactSummary[], string>(__TAURI_INVOKE("list_github_artifacts", { args })),
	listGithubEnvironments: (args: GithubListArgs) => typedError<EnvironmentSummary[], string>(__TAURI_INVOKE("list_github_environments", { args })),
	listGithubPendingDeployments: (args: GithubRunArgs) => typedError<PendingDeploymentSummary[], string>(__TAURI_INVOKE("list_github_pending_deployments", { args })),
	rerunFailedGithubWorkflow: (args: GithubRerunFailedArgs) => typedError<null, string>(__TAURI_INVOKE("rerun_failed_github_workflow", { args })),
	listWorktreeLeases: (args: ListWorktreeLeasesArgs) => typedError<WorktreeLeaseView[], string>(__TAURI_INVOKE("list_worktree_leases", { args })),
	listAuditRecords: (args: ListAuditRecordsArgs) => typedError<AuditRecordView[], string>(__TAURI_INVOKE("list_audit_records", { args })),
	listQualityGateResults: (args: ListEvidenceArgs) => typedError<QualityGateResultView[], string>(__TAURI_INVOKE("list_quality_gate_results", { args })),
	listReviewFindings: (args: ListEvidenceArgs) => typedError<ReviewFindingView[], string>(__TAURI_INVOKE("list_review_findings", { args })),
};

/* Types */
export type AppDiagnostics = {
	app_version: string,
	/**
	 *  Kept in sync by hand with the root `Cargo.toml`'s `[workspace]
	 *  members` list (currently 21 library crates + this application
	 *  shell). Not worth a build-time Cargo.toml parser for a diagnostics
	 *  display value at this phase.
	 */
	workspace_crate_count: number,
	/**
	 *  The workspace's declared MSRV (`rust-version` in the root
	 *  `Cargo.toml`), read via Cargo's `CARGO_PKG_RUST_VERSION` build-time
	 *  environment variable -- not the compiler that happened to build
	 *  this binary, which Cargo does not expose to running code.
	 */
	minimum_rust_version: string,
	dev_mode: boolean,
	/**
	 *  Proves a real `nacc-domain` strong ID -- not a plain string or a
	 *  bare UUID -- serializes correctly across the IPC boundary and
	 *  deserializes back into a matching TypeScript type.
	 */
	sample_workflow_run_id: WorkflowRunId,
	/**
	 *  The applied SQLite schema version (master plan S4.4), formatted for
	 *  display. Proves `nacc-storage`'s migrations genuinely ran against
	 *  the real on-disk database this process opened, not an in-memory
	 *  test double.
	 */
	storage_schema_version: string,
	/**
	 *  How many audit records this command has ever written for
	 *  `sample_workflow_run_id`, read back fresh on every call. A real,
	 *  live query result: it increments by one each time this command
	 *  runs, which is directly observable by calling it twice in the same
	 *  running app -- not a static or precomputed value.
	 */
	diagnostics_requests_recorded: number,
};

/** Identifies one approval request/decision attached to a workflow node (master plan S12, S14.1). */
export type ApprovalId = string;

export type ApprovalView = {
	id: ApprovalId,
	node_run_id: NodeRunId,
	node_key: string,
	summary: string,
	/**  `None` while the gate is still open. */
	decision: string | null,
	decided_at_millis: string | null,
};

export type ArtifactSummary = {
	id: string,
	name: string,
	size_in_bytes: string,
	expired: boolean,
	created_at: string,
	expires_at: string,
	workflow_run_id: string | null,
	head_sha: string | null,
	archive_download_url: string,
};

/** Identifies one attempt of a `NodeRun` -- a node may be retried, and each retry is its own attempt (master plan S7). */
export type AttemptId = string;

/** Identifies one entry in the audit trail (master plan S7's `AuditEvent`, S22's audit-record fields). */
export type AuditEventId = string;

export type AuditRecordView = {
	id: AuditEventId,
	actor: string,
	action: string,
	project_id: ProjectId | null,
	workflow_run_id: WorkflowRunId | null,
	node_run_id: NodeRunId | null,
	attempt_id: AttemptId | null,
	requested_provider: ProviderId | null,
	actual_provider: ProviderId | null,
	requested_model: ModelId | null,
	actual_model: ModelId | null,
	effective_reasoning_level: ReasoningLevel | null,
	effective_permission_profile: PermissionProfile | null,
	command_executable: string | null,
	redacted_arguments: string[],
	working_directory: string | null,
	created_at_millis: string,
};

/**
 *  Point-in-time sign-in status for one provider. Not persisted: the
 *  adapters check the native credential store's *existence* live on every
 *  call (contents never read, master plan S8.4), so a stored answer would
 *  only go stale; the frontend labels this as "checked now".
 */
export type AuthProbeView = {
	provider: ProviderId,
	authenticated: boolean,
	account_label: string | null,
	detail: string | null,
	checked_at_millis: string,
};

export type BranchSummary = {
	name: string,
	commit_sha: string,
	protected: boolean,
};

/**
 *  IPC view over a [`CapabilitySnapshot`] (master plan S8.3): the timestamped
 *  facts a GUI needs to enable or disable model-aware controls honestly.
 */
export type CapabilitySnapshotView = {
	provider: ProviderId,
	installed: boolean,
	version: string | null,
	authenticated: boolean,
	/**
	 *  Adapter-declared health, snake_case ("ready", "not_installed",
	 *  "unauthenticated", ...). A GUI shows it; nothing infers readiness.
	 */
	health: string,
	models: ModelCapabilityView[],
	checked_at_millis: string,
};

export type CheckPrerequisitesArgs = {
	/**
	 *  Probe `gh` too? The wizard asks, because `gh` detection shells out
	 *  and the wizard should only spend that on steps the user is on.
	 */
	include_gh: boolean,
};

export type CheckRunSummary = {
	id: string,
	name: string,
	status: string,
	conclusion: string | null,
	details_url: string | null,
	started_at: string | null,
	completed_at: string | null,
	app_name: string | null,
};

export type CheckWorkspaceArgs = {
	/**  Absolute path to validate. */
	path: string,
};

export type CheckpointView = {
	sequence: number,
	state: RunState,
	detail: string,
	created_at_millis: string,
};

export type CreateRoleProfileArgs = {
	name: string,
	role_kind: RoleKind,
	provider_id: ProviderId | null,
	model_id: ModelId | null,
	thinking_mode: ThinkingMode,
	reasoning_level: ReasoningLevel,
	permission_profile: PermissionProfile,
	/**  A user-typed account preference label -- never a credential (S11). */
	account_label: string | null,
	/**
	 *  The row's fallback chain, consulted only when no primary provider is
	 *  assigned and the node declares none of its own (S11, S14.4).
	 */
	fallbacks: NodeFallback[],
};

export type DecideApprovalArgs = {
	run_id: WorkflowRunId,
	approval_id: ApprovalId,
	approved: boolean,
	/**
	 *  Who decided. Required even for approval: "who let this run write to
	 *  the repository" must have an answer (master plan S22).
	 */
	by: string,
	/**  Required when rejecting, ignored otherwise. */
	reason: string | null,
	/**  Whether to continue the run immediately after approving. */
	resume_after: boolean,
};

export type DetectProviderArgs = {
	provider_id: ProviderId,
};

export type EnvironmentSummary = {
	id: string,
	name: string,
	url: string,
	html_url: string,
	can_admins_bypass: boolean | null,
	protection_rule_count: number,
};

/**
 *  The normalized event vocabulary (master plan S8.2): what every provider
 *  adapter's raw output is mapped to before workflow logic or the audit
 *  trail ever sees it. "Raw provider streams may be retained in redacted
 *  diagnostic logs, but workflow decisions must use normalized events" --
 *  this enum is deliberately closed (no `Other(String)` escape hatch) for
 *  that reason: an adapter that produces something outside this vocabulary
 *  has a real mapping gap to fix, not a case to silently pass through.
 */
export type EventType = "session_started" | "assistant_text_delta" | 
/**
 *  Reasoning *status* only -- master plan S18: "Do not store or expose
 *  hidden chain-of-thought." This variant exists to say reasoning is
 *  happening, never to carry its content.
 */
"reasoning_status" | "tool_requested" | "tool_approved" | "tool_denied" | "tool_started" | "tool_output_delta" | "file_changed" | "command_started" | "command_output" | "command_completed" | "plan_artifact_emitted" | "handoff_emitted" | "usage_updated" | "approval_requested" | "warning" | "recoverable_error" | "terminal_error" | "session_completed" | "session_cancelled";

export type FailedRunEvidence = {
	run_id: string,
	job_id: string,
	job_name: string,
	classification: FailureClass,
	matched_evidence: string | null,
	log_excerpt: string,
};

/**
 *  The failure classes the master plan's CI/CD flow distinguishes. `Unknown`
 *  is a real answer: an unclassified failure needs a human, not a rerun.
 */
export type FailureClass = "product_defect" | "stale_test" | "flakiness" | "environment" | "dependency" | "workflow_config" | "secret_missing" | "external_service" | "timeout" | "resource_exhaustion" | "permissions" | "unknown";

export type GithubAuthStatus = {
	authenticated: boolean,
	login: string | null,
};

export type GithubChecksArgs = {
	repository: string,
	commit_sha: string,
	limit: number,
};

export type GithubListArgs = {
	repository: string,
	limit: number,
};

export type GithubRepositoryArgs = {
	repository: string,
};

export type GithubRerunFailedArgs = {
	repository: string,
	run_id: string,
	approved_by: string,
	reason: string,
};

export type GithubRunArgs = {
	repository: string,
	run_id: string,
};

export type ListAuditRecordsArgs = {
	workflow_run_id: WorkflowRunId | null,
	limit: number | null,
};

export type ListEvidenceArgs = {
	workflow_run_id: WorkflowRunId | null,
	node_run_id: NodeRunId | null,
	limit: number | null,
};

export type ListWorktreeLeasesArgs = {
	project_id: ProjectId | null,
	active_only?: boolean,
	limit: number | null,
};

/**
 *  IPC view over one discovered model: exactly what the adapter reported
 *  (S10.1/S2.7 -- shown as-is, never normalized into a NACC-owned catalog).
 *  `reasoning_levels` is the honest list a GUI may offer for the model;
 *  an empty list means "no reasoning control has been verified".
 */
export type ModelCapabilityView = {
	id: string,
	display_name: string,
	reasoning_levels: ReasoningLevel[],
	thinking: ThinkingMode,
	/**
	 *  Context window in tokens as reported, stringified for IPC. `None`
	 *  means the provider did not report one -- shown as unknown, not guessed.
	 */
	context_window_tokens: string | null,
};

/**
 *  An exact, provider-reported model identifier -- e.g. `"claude-fable-5"`
 *  or `"gpt-5.4"`. Deliberately a newtype around `String`, not an enum:
 *  master plan S2.7 and S9.5 both require NACC to display exactly what a
 *  provider returns rather than assume or hard-code a spelling.
 */
export type ModelId = string;

/**
 *  A node that can be re-run, in order, when the primary assignment cannot
 *  serve the request. Empty means "no fallback declared" -- which is a real
 *  answer, not a missing one: the run then fails visibly instead of
 *  silently switching providers.
 */
export type NodeFallback = {
	provider_id: ProviderId,
	model_id: ModelId | null,
	/**  Shown to the user when the fallback is actually taken. */
	reason: string,
};

/** Identifies one execution of a workflow node within a `WorkflowRun` (master plan S7). */
export type NodeRunId = string;

export type NodeRunView = {
	id: NodeRunId,
	node_key: string,
	title: string,
	state: NodeState,
	attempts: number,
	/**  Whether this node must be approved by a human before it runs. */
	requires_approval: boolean,
	last_detail: string | null,
};

/**
 *  State of one node within a run. Closed, like every other state machine
 *  here: the engine decides transitions, and a caller that sees an
 *  unfamiliar value has a version mismatch to fix rather than a case to
 *  guess at.
 */
export type NodeState = 
/**  Not yet eligible (dependencies incomplete). */
"pending" | "running" | "succeeded" | 
/**  Exhausted its attempts, or failed non-retryably. */
"failed" | 
/**  A dependency failed, so this node will never run. */
"skipped" | "cancelled";

export type PendingDeploymentSummary = {
	environment_id: string,
	environment_name: string,
	wait_timer: number,
	current_user_can_approve: boolean,
	reviewer_logins: string[],
};

/**
 *  Permission profile a running agent operates under (master plan S12.1).
 *  Enforced by `nacc-policy` before every privileged operation; never
 *  decorative.
 */
export type PermissionProfile = "read_only" | "plan_only" | "autonomous_worktree" | "repository_maintainer" | "ci_maintainer" | "release_candidate" | 
/**
 *  Per-run, time-limited override. Master plan S12.1: "no ability to
 *  make itself persistent" -- `nacc-policy` must enforce the expiry,
 *  this variant only names the state.
 */
"temporary_danger_full_access";

/**
 *  One prerequisite's honest state: detected with a version, or explicitly
 *  not detected. There is no "assumed fine" third state.
 */
export type PrerequisiteView = {
	name: string,
	detected: boolean,
	/**  The tool's own version string, verbatim (e.g. "git version 2.53.0"). */
	version: string | null,
	/**  Why detection did not run or what failed, when worth showing. */
	detail: string | null,
};

/** Identifies a NACC-managed project (a bound repository plus its NACC-owned configuration). */
export type ProjectId = string;

/**
 *  A provider identifier. Unlike the UUID-backed IDs above, this is a
 *  small, stable, closed enumeration -- new providers are added to NACC's
 *  own code, not created by users at runtime, so a UUID would be the wrong
 *  shape here. Per master plan S2.7 ("do not hard-code marketing names as
 *  architectural constants"), this identifies the *adapter*, not a model:
 *  exact model IDs are always provider-reported strings, never hard-coded
 *  (see `ModelId` below).
 */
export type ProviderId = "claude" | "codex" | "antigravity" | "copilot" | "opencode";

/**
 *  IPC view over [`ProviderInstallation`]: same shape as the stored record
 *  with string timestamps (the same convention `RoleProfileView` uses, so
 *  the webview never receives a bare integer epoch it must format).
 */
export type ProviderInstallationView = {
	provider: ProviderId,
	runtime: RuntimeLocation,
	installed: boolean,
	executable_path: string | null,
	version: string | null,
	detected_at_millis: string,
};

export type PullRequestSummary = {
	number: number,
	title: string,
	state: string,
	is_draft: boolean,
	head_ref_name: string,
	base_ref_name: string,
	url: string,
	author_login: string | null,
	merge_state_status: string | null,
};

export type QualityGateResultView = {
	workflow_run_id: WorkflowRunId,
	node_run_id: NodeRunId,
	attempt_id: AttemptId | null,
	gate: string,
	command: string,
	passed: boolean,
	exit_code: number | null,
	timed_out: boolean,
	duration_ms: string,
	log_tail: string,
	created_at_millis: string,
};

/**
 *  A deterministic command that a workflow node declares as completion
 *  evidence. This is intentionally a declarative domain contract rather than
 *  an executable policy: `nacc-quality` owns spawning and policy checks while
 *  the orchestrator owns when declared gates become part of node completion.
 */
export type QualityGateSpec = {
	/**  Stable within one node and used to correlate durable evidence. */
	name: string,
	/**  Exact executable plus arguments. This is never a shell command string. */
	argv: string[],
	/**  Per-gate execution ceiling in seconds. `u32` stays IPC-safe for specta. */
	timeout_secs: number,
	/**
	 *  Required gates will eventually participate in the node completion
	 *  predicate; optional gates remain evidence without blocking completion.
	 */
	required: boolean,
};

export type ReasonArgs = {
	run_id: WorkflowRunId,
	reason: string,
};

/**
 *  Canonical reasoning-effort scale (master plan S10.1). Every provider
 *  adapter maps this to whatever it natively supports; a provider that
 *  cannot honor a requested level must say so explicitly rather than
 *  silently clamp -- see `nacc_provider_core::CapabilitySnapshot`.
 * 
 *  This is switch 4 of the Role Matrix's four independently settable
 *  per-role controls (role / model / thinking / reasoning effort).
 */
export type ReasoningLevel = "auto" | "off" | "minimal" | "low" | "medium" | "high" | "extra_high" | "maximum";

export type RepositorySummary = {
	name_with_owner: string,
	default_branch: string | null,
	is_private: boolean,
	url: string,
};

export type ReviewFindingView = {
	workflow_run_id: WorkflowRunId,
	node_run_id: NodeRunId,
	attempt_id: AttemptId | null,
	node_key: string,
	file: string,
	line: number | null,
	severity: ReviewSeverityView,
	summary: string,
	evidence: string,
	created_at_millis: string,
};

export type ReviewSeverityView = "blocker" | "major" | "minor" | "note";

/**
 *  The role catalog (Phase 0 plan addendum's "locked GUI requirement",
 *  binding on every later phase): every row is independently configurable
 *  and provider-swappable, and users can add custom roles beyond this
 *  built-in list. Deliberately open (`Custom(String)`), unlike the closed,
 *  provider-normalized event vocabulary in `nacc-events` -- a role is a
 *  user-facing organizational concept, not something adapters must map
 *  output onto.
 */
export type RoleKind = "brain_main_orchestrator" | "architect_planner" | "repository_explorer" | "external_researcher" | "frontend_implementer" | "backend_implementer" | "database_migration_implementer" | "test_engineer" | "qa_reviewer" | "general_code_reviewer" | "security_reviewer" | "accessibility_ux_reviewer" | "performance_reviewer" | "documentation_writer" | "refactor_migration_specialist" | "ci_cd_investigator" | "integrator" | "release_manager" | { custom: string };

/** Identifies one configured Role Matrix row (master plan S11). */
export type RoleProfileId = string;

export type RoleProfileMutation = {
	profile: RoleProfileView,
};

export type RoleProfileUpdate = {
	name: string,
	role_kind: RoleKind,
	provider_id: ProviderId | null,
	model_id: ModelId | null,
	thinking_mode: ThinkingMode,
	reasoning_level: ReasoningLevel,
	permission_profile: PermissionProfile,
	account_label?: string | null,
	fallbacks?: NodeFallback[],
	enabled: boolean,
};

export type RoleProfileView = {
	id: RoleProfileId,
	name: string,
	role_kind: RoleKind,
	provider_id: ProviderId | null,
	model_id: ModelId | null,
	thinking_mode: ThinkingMode,
	reasoning_level: ReasoningLevel,
	permission_profile: PermissionProfile,
	account_label: string | null,
	fallbacks: NodeFallback[],
	enabled: boolean,
	created_at_millis: string,
	updated_at_millis: string,
};

export type RunIdArgs = {
	run_id: WorkflowRunId,
};

export type RunSnapshotView = {
	run: WorkflowRunView,
	nodes: NodeRunView[],
	approvals: ApprovalView[],
	checkpoints: CheckpointView[],
	/**
	 *  `u32`, not `usize`: specta refuses to export pointer-width integers
	 *  (precision loss across the IPC boundary), matching `attempts`/`sequence`.
	 */
	pending_approval_count: number,
	finished: boolean,
};

/**
 *  Lifecycle state of one workflow run (master plan S14.1's durable state
 *  machine). Every variant is terminal-safe: `Paused` and `AwaitingApproval`
 *  mean "resumable", and `Interrupted` is the state a crash leaves behind
 *  for reconciliation to pick up.
 */
export type RunState = "pending" | "running" | 
/**  Deliberately stopped by a user; resumable. */
"paused" | 
/**  Blocked on a human approval gate (master plan S12.2). */
"awaiting_approval" | 
/**
 *  The process died mid-run. Reconciliation turns this back into a
 *  resumable run rather than pretending it failed.
 */
"interrupted" | "succeeded" | "failed" | "cancelled";

/**
 *  What runtime location a provider's CLI is being probed/launched under.
 *  Kept intentionally small in Phase 1; `nacc-runtime` (Phase 3) owns the
 *  real WSL2/Docker abstraction this references.
 */
export type RuntimeLocation = "native_windows" | "wsl2" | "docker";

export type SaveTemplateArgs = {
	name: string,
	description: string,
	nodes: WorkflowNode[],
};

export type StartRunArgs = {
	project_id: ProjectId,
	template_name: string,
	/**
	 *  Absolute path the agents work in, chosen by the user. Required: an
	 *  implicit working directory is how an agent ends up writing somewhere
	 *  nobody asked for.
	 */
	workspace: string,
	/**
	 *  Absolute path to a directory under which a fresh git worktree lease
	 *  is allocated for this run (master plan S16). When set, every node of
	 *  the run works in that isolated worktree and the primary checkout is
	 *  never touched. `None` runs directly in `workspace`.
	 */
	worktrees_root: string | null,
};

export type TemplateNameArgs = {
	name: string,
};

/**
 *  Canonical thinking-mode control (master plan S10.2). Deliberately
 *  distinct from `ReasoningLevel` -- switches 3 and 4 of the Role Matrix
 *  are orthogonal and must never move each other (mission-critical
 *  requirement recorded in the Phase 0 plan addendum).
 */
export type ThinkingMode = "auto" | "on" | "off" | 
/**
 *  The provider manages this internally and exposes no control; show
 *  "Managed by provider" in the GUI rather than a live toggle.
 */
"managed_by_provider" | 
/**
 *  The selected provider/model has no thinking concept at all; the
 *  GUI must disable the control, not merely default it to Off.
 */
"unsupported";

/**
 *  One normalized event, as the run console lists it. The payload is carried
 *  as JSON text: its shape is provider-driven and the GUI shows it verbatim
 *  rather than pretending to know every variant's fields (master plan S8.2).
 */
export type WorkflowEventView = {
	event_type: EventType,
	payload_json: string,
	created_at_millis: string,
};

export type WorkflowJobSummary = {
	database_id: string,
	name: string,
	status: string,
	conclusion: string | null,
	started_at: string | null,
	completed_at: string | null,
	url: string,
	steps: WorkflowStepSummary[],
};

/**  One node of a workflow template (master plan S14.2's DAG). */
export type WorkflowNode = {
	/**  Stable within a template; what `depends_on` and the UI refer to. */
	key: string,
	title: string,
	role: RoleKind,
	/**  Node keys that must succeed before this node runs. */
	depends_on: string[],
	/**  Prompt/instruction handed to the role's agent. */
	instruction: string,
	/**
	 *  The permission profile this node runs under. Declared per node rather
	 *  than per run because master plan S12.1's profiles are per-operation:
	 *  an integrator step writes to the repository while the explorer steps
	 *  beside it must not.
	 */
	permission_profile_hint: PermissionProfile,
	/**  Never retried automatically when false (e.g. a destructive step). */
	retryable: boolean,
	/**
	 *  Requires a recorded human approval before it runs (S12.2's
	 *  always-approval-gated operations).
	 */
	requires_approval: boolean,
	/**
	 *  Ceiling for one attempt of this node, in seconds. `None` means the
	 *  executor's own default applies -- the declaration is per node because
	 *  a quick review step and a long implementation step have genuinely
	 *  different natural durations (master plan S14's node contracts). `u32`
	 *  because specta refuses pointer-width integers across IPC.
	 */
	timeout_secs?: number | null,
	/**
	 *  Machine-readable deterministic checks declared by this node. Older
	 *  persisted templates predate this field, so absence must remain exactly
	 *  equivalent to declaring no quality gates.
	 */
	quality_gates?: QualityGateSpec[],
	fallbacks: NodeFallback[],
};

/** Identifies one execution of a workflow template. */
export type WorkflowRunId = string;

export type WorkflowRunSummary = {
	database_id: string,
	name: string,
	workflow_name: string,
	status: string,
	conclusion: string | null,
	event: string,
	head_branch: string | null,
	head_sha: string,
	url: string,
	created_at: string,
	updated_at: string,
};

export type WorkflowRunView = {
	id: WorkflowRunId,
	project_id: ProjectId,
	template_name: string,
	state: RunState,
	note: string | null,
	created_at_millis: string,
	updated_at_millis: string,
};

export type WorkflowStepSummary = {
	number: number,
	name: string,
	status: string,
	conclusion: string | null,
	started_at: string | null,
	completed_at: string | null,
};

export type WorkflowTemplateDefinitionView = {
	name: string,
	description: string,
	nodes: WorkflowNode[],
	version: number,
	is_built_in: boolean,
};

export type WorkflowTemplateView = {
	name: string,
	description: string,
	node_keys: string[],
	/**  Storage edition of this graph; advances when the definition changes. */
	version: number,
	/**
	 *  Built-in presets are protected: the GUI can run them but never
	 *  replace or delete them.
	 */
	is_built_in: boolean,
};

export type WorkspaceCheckView = {
	path: string,
	is_git_repo: boolean,
};

/** Identifies one NACC-allocated Git worktree lease (master plan S16's worktree lifecycle). */
export type WorktreeLeaseId = string;

export type WorktreeLeaseView = {
	id: WorktreeLeaseId,
	project_id: ProjectId,
	workflow_run_id: WorkflowRunId | null,
	node_run_id: NodeRunId | null,
	path: string,
	branch: string,
	base_commit: string,
	head_commit: string | null,
	state: WorktreeState,
	owner_process_id: number | null,
	quarantine_reason: string | null,
	created_at_millis: string,
	updated_at_millis: string,
};

/**
 *  Lifecycle state of a worktree lease (master plan S16: allocation,
 *  integration, release, quarantine). Closed and exhaustive on purpose: the
 *  whole point of the lease record is that "what happened to this
 *  worktree?" always has exactly one answer.
 */
export type WorktreeState = "active" | "quarantined" | "released";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

